#!/bin/bash

if [ ! -d ~/.cache/dchelp ]; then
    mkdir ~/.cache/dchelp
    chmod 775 ~/.cache/dchelp
fi

if [ ! -d ~/.config/dchelp ]; then
    mkdir ~/.config/dchelp
    chmod 775 ~/.config/dchelp
    touch ~/.config/dchelp/data.json
    chmod 775 ~/.config/dchelp/data.json
    echo "[]" >> ~/.config/dchelp/data.json
fi

$(which python) /usr/local/dchelp/main.py $*